### ISSUE TITLE
Variable VALIDATEMODEL is undefined. 

### ISSUE THREAD

**Issue by saintybalboa** [coldbox-modules/cbox-validation#18]
Hi,

I've dropped cbvalidation into the modules folder and when I try to use the validator in any handler i get the following message: 

> Variable VALIDATEMODEL is undefined. 

I'm currently running Coldfusion version 9,0,2,282541  

Here's the valdiation script:
```
 <!---  validation rules / constraints --->
  <cfset local.rules = {
                password = {required=true, requiredMessage="Please enter a value"},
                confirm_password = {
                                    required=true, requiredMessage="Please enter a value",
                                    SameAs= "password", SameAsMessage= "Please enter a matching password"
                                }
         }>

  <!--- Validate --->
  <cfset local.validator = validateModel(rc, local.rules )>
```

Here's the stack trace:
```
coldfusion.runtime.UndefinedVariableException: Variable VALIDATEMODEL is undefined.
    at coldfusion.runtime.CfJspPage._get(CfJspPage.java:303)
    at coldfusion.runtime.CfJspPage._get(CfJspPage.java:283)
    at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1494)
    at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1471)
    at cfAuthController2ecfc96573382$funcPASSWORDRESETCONFIRMACTION.runFunction(D:\webpages\cms\handlers\AuthController.cfc:77)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2547)
    at cfEventHandler2ecfc2062222502$func_PRIVATEINVOKER.runFunction(D:\webpages\cms\coldbox\system\EventHandler.cfc:85)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
    at cfController2ecfc1432567149$funcINVOKER.runFunction(D:\webpages\cms\coldbox\system\web\Controller.cfc:795)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2547)
    at cfController2ecfc1432567149$func_RUNEVENT.runFunction(D:\webpages\cms\coldbox\system\web\Controller.cfc:633)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2547)
    at cfController2ecfc1432567149$funcRUNEVENT.runFunction(D:\webpages\cms\coldbox\system\web\Controller.cfc:425)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:517)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:496)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:355)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2301)
    at cfBootstrap2ecfc1889428779$funcPROCESSCOLDBOXREQUEST.runFunction(D:\webpages\cms\coldbox\system\Bootstrap.cfc:200)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
    at cfBootstrap2ecfc1889428779$funcONREQUESTSTART.runFunction(D:\webpages\cms\coldbox\system\Bootstrap.cfc:359)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
    at cfapplication2ecfc1226568062$funcONREQUESTSTART.runFunction(D:\webpages\cms\application.cfc:94)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
    at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:88)
    at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:258)
    at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:349)
    at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)
    at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
    at coldfusion.filter.PathFilter.invoke(PathFilter.java:94)
    at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70)
    at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:79)
    at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
    at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
    at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
    at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
    at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
    at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
    at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126)
    at coldfusion.CfmServlet.service(CfmServlet.java:200)
    at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
    at jrun.servlet.FilterChain.doFilter(FilterChain.java:86)
    at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
    at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
    at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
    at jrun.servlet.FilterChain.service(FilterChain.java:101)
    at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106)
    at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42)
    at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286)
    at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543)
    at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203)
    at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428)
    at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)
```

Any help would be much appreciated

**Comment by saintybalboa** [comment]
Just realised the validation package is only available in Coldfusion 10+
